name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      
      - name: Publish
        shell: bash
        env:
          BUNNY_STORAGE_KEY: ${{ secrets.BUNNY_STORAGE_KEY }}
          BUNNY_STORAGE_ZONE: ${{ secrets.BUNNY_STORAGE_ZONE }}
        run: |
         # TODO: Use personal fork
         sudo npm install -g bnycdn
         bnycdn key set default "$BUNNY_STORAGE_KEY" -t storages
         bnycdn cp -R ./public ./$BUNNY_STORAGE_ZONE


